### PR TITLE
fix: add buffer

### PR DESCRIPTION
**Pull request by hugomrdias**

### CODE REVIEW

**Review by vmx — APPROVED** [review]

**Comment by mikeal** [comment]
What does this fix?

Isn’t the `buffer` module already pulled in to polyfill the Buffer API by bundlers? This potentially introduces a condition in which there is more than one Buffer module in a bundle due to version discrepancies.

**Comment by hugomrdias** [comment]
> Isn’t the buffer module already pulled in to polyfill the Buffer API by bundlers?

this will be removed by bundlers plus current polyfill are outdated

> This potentially introduces a condition in which there is more than one Buffer module in a bundle due to version discrepancies.

this was already happening cause same module explicitly require others don't

**Comment by mikeal** [comment]
sigh...

I’d love to get off of `Buffer` but it’s proving to be much more difficult than I had anticipated. The vast majority of the polyfill is never used but actually removing an interface that is passed around so much has proven impractical.

**Comment by hugomrdias** [comment]
me too i have being looking at your bytesish module a lot, but as you said its hard plus we are now using bufferlist in multiple places.
would love to brainstorm this

**Comment by mikeal** [comment]
ya, i’ve used bytesish all over the place but it doesn’t quite solve the problem, it just moves around the responsibility and makes it a little easier to not rely on anything.

maybe we should start a thread somewhere about all the different approaches we might consider. i’m sure @rvagg has thought about this quite a bit as well, and there are a few things that `bl` does that are missing from **all** the binary interfaces we have available.

**Pull request merged**
